name: Build and Test
on: [push]
jobs:
  deploy_source:
    name: Build and Test
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
      - name: Unit test
        run: yarn test
      - name: Run build
        run: yarn build
